import random
import plotly.figure_factory as ff
import pandas
import statistics

file1 = pandas.read_csv('studentMarks.csv')
file2 = pandas.read_csv('data1.csv')
file3 =pandas.read_csv('data2.csv')
file4 = pandas.read_csv('data3.csv')
data = file1['Math_score'].tolist()
data2 = file2['Math_score'].tolist()
data3 = file3['Math_score'].tolist()
data4 = file4['Math_score'].tolist()
fig = ff.create_distplot([data],['Student Marks'],show_hist=False)
fig.show()
print('original data')
mean = statistics.mean(data)
print(mean)
median = statistics.median(data)
print(median)
mode = statistics.mode(data)
print(mode)
standardDev = statistics.stdev(data)
print(standardDev)

print('data1')
mean1 = statistics.mean(data2)
print(mean1)
median1 = statistics.median(data2)
print(median1)
mode1 = statistics.mode(data2)
print(mode1)
standardDev1 = statistics.stdev(data2)
print(standardDev1)

print('data2')
mean2 = statistics.mean(data3)
print(mean2)
median2 = statistics.median(data3)
print(median1)
mode2 = statistics.mode(data3)
print(mode2)
standardDev2 = statistics.stdev(data3)
print(standardDev2)

print('data3')
mean3 = statistics.mean(data4)
print(mean3)
median3 = statistics.median(data4)
print(median3)
mode3 = statistics.mode(data4)
print(mode3)
standardDev3 = statistics.stdev(data4)
print(standardDev3)